version: "{branch} {build}"

max_jobs: 1

environment:
  matrix:
  - JAVA_HOME: C:\Program Files\Java\jdk1.8.0

build:
  verbosity: detailed

build_script:
- gradlew.bat assemble --info --no-daemon

test_script:
- gradlew.bat check --info --no-daemon

cache:
- C:\Users\appveyor\.gradle

matrix:
  fast_finish: true
