version: "{branch} {build}"

max_jobs: 1

environment:
  matrix:
  # don't let this fool you, we still build to target java7
  - JAVA_HOME: C:\Program Files\Java\jdk1.8.0

install:
# set PATH
- SET PATH=C:\google\google-cloud-sdk\bin;%JAVA_HOME%\bin;%PATH%

# download Cloud SDK
- appveyor DownloadFile https://dl.google.com/dl/cloudsdk/channels/rapid/GoogleCloudSDKInstaller.exe
# install Cloud SDK
- GoogleCloudSDKInstaller.exe /S /noreporting /nostartmenu /nodesktop /logtofile /D=C:\google
# prepare for non-interactive Cloud SDK components update
- gcloud.cmd components copy-bundled-python>>python_path.txt && SET /p CLOUDSDK_PYTHON=<python_path.txt && DEL python_path.txt
# update all Cloud SDK components
- gcloud.cmd components update --quiet
# add App Engine component to Cloud SDK
- gcloud.cmd components install app-engine-java --quiet
# add beta component to Cloud SDK for Cloud Debugger
- gcloud.cmd components install beta --quiet

build:
  verbosity: detailed

build_script:
- gradlew.bat assemble --info --no-daemon

test_script:
- gradlew.bat check --info --no-daemon

cache:
- C:\Users\appveyor\.gradle

matrix:
  fast_finish: true
