/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ffc.airsync.gui.drawable;

import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Thanachai Thongkum
 */
public class CoutDownMessage extends javax.swing.JPanel {

    /**
     * Creates new form OtpShow
     */
    private int count = 0;
    private CallbackCountDone callback;

    interface CallbackCountDone {

        void callback();
    }

    public CoutDownMessage(CallbackCountDone callback) {
        this.callback = callback;
        // setBackground(new Color(204, 255, 204));
        initComponents();
    }

    public void setMessage(String message, int couter) {
        this.message.setText(message);
        count = couter;
        this.couter.setText(Integer.toString(couter));
    }

    public void startCount() {
        new Thread() {
            boolean working = true;

            @Override
            public void run() {
                while (working) {
                    try {
                        couter.setText(Integer.toString(count--));
                        if (count == 0) {
                            working = false;
                        }
                        Thread.sleep(1000);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(CoutDownMessage.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                callback.callback();
            }
        }.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        message = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        couter = new javax.swing.JLabel();

        setBackground(new java.awt.Color(253, 253, 253));

        message.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        message.setText("message");

        jPanel1.setBackground(new java.awt.Color(253, 253, 253));

        couter.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        couter.setText("couter");
        couter.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(couter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 21, Short.MAX_VALUE)
                .addComponent(couter))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(message, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(message)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel couter;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel message;
    // End of variables declaration//GEN-END:variables
}
