/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ffc.airsync.gui.drawable;

import java.awt.Color;
import java.awt.Dimension;

/**
 * @author Thanachai Thongkum
 */
public class StatusProgress extends javax.swing.JPanel {


    /**
     * Creates new form StatusProgress
     */
    public StatusProgress() {
        setBackground(new Color(204, 255, 204));
        initComponents();
    }

    public StatusProgress(int width, int height) {
        this();
        setPreferredSize(new Dimension(width, height));
    }

    public void setValue(int value) {
        jProgressBar.setValue(value);
        label.updateUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label = new javax.swing.JTextPane();
        jProgressBar = new javax.swing.JProgressBar();

        setBackground(new java.awt.Color(253, 253, 253));
        setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        setName(""); // NOI18N

        label.setBackground(new java.awt.Color(253, 253, 253));
        label.setBorder(null);
        label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label.setForeground(new java.awt.Color(0, 102, 0));

        jProgressBar.setBackground(new java.awt.Color(255, 255, 255));
        jProgressBar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jProgressBar.setForeground(new java.awt.Color(76, 189, 148));
        jProgressBar.setStringPainted(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label)
            .addComponent(jProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JProgressBar jProgressBar;
    public javax.swing.JTextPane label;
    // End of variables declaration//GEN-END:variables
}
